swagger: '2.0'
info:
    description: 'Contains all available API endpoints in this codebase'
    version: '1.0.0'
    title: 'Bank Argent API documentation'
    termsOfService: 'https://smartbear.com/terms-of-use/'
    contact:
        email: 'apiteam@swagger.io'
host: localhost:3001
basePath: /api/v1
schemes:
    - 'http'
paths:
    /user/transactions:
        post:
            security:
                - Bearer: []
            tags:
                - User Transations
            summary: 'User Transactions API'
            description: 'Show all month's transactions'
            operationId: 'showMonthTansactions'
            produces:
                - 'application/json'
            parameters:
              - in: 'header'
                  name: 'Authorization'
                  description: 'Attach Bearer JWT token'
                  required: true
            responses:
                '200':
                    description: User transactions retrieved successully
                    schema:
                        type: 'array'
                        items:
                            $ref: '#definitions/Transaction'
                '400':
                    description: Invalid Fields
                '500':
                    description: Internal Server Error
    /user/transactions/{transactionId}:
        post:
            security:
                - Bearer: []
            tags:
                - User Transations
            summary: 'User Transactions API'
            description: 'Show a transaction details'
            operationId: 'showTansactionDetails'
            produces:
                - 'application/json'
            parameters:
              - in: 'header'
                  name: 'Authorization'
                  description: 'Attach Bearer JWT token'
                  required: true
              - in: body
                  name: body
                  description: Transaction Payload
                  required: true
                  schema:
                    $ref: '#/definitions/TransactionId'
            responses:
                '200':
                    description: User transaction retrieved successully
                    schema:
                        type: 'object'
                        items:
                            $ref: '#/definition/TransactionResponse/'
                '400':
                    description: Invalid Fields
                '500':
                    description: Internal Server Error
        put:
            security:
                - Bearer: []
            tags:
                - User Transations
            summary: 'User Transactions API'
            description: 'Show all month's transactions'
            operationId: 'showMonthTansactions'
            produces:
                - 'application/json'
            parameters:
              - in: 'header'
                  name: 'Authorization'
                  description: 'Attach Bearer JWT token'
                  required: true
              - in: body
                  name: body
                  description: Update transaction attributes
                  required: true
                  schema:
                    $ref: '#/definition/Transaction'
            responses:
                '200':
                    description: User transaction updated successully
                    schema:
                        type: 'object'
                        items:
                            $ref: '#/definition/TransactionChangeResponse'
                '400':
                    description: Invalid Fields
                '500':
                    description: Internal Server Error
        delete:
            security:
                - Bearer: []
            tags:
                - User Transations
            summary: 'User Transactions API'
            description: 'Show all month's transactions'
            operationId: 'showMonthTansactions'
            produces:
                - 'application/json'
            parameters:
              - in: 'header'
                  name: 'Authorization'
                  description: 'Attach Bearer JWT token'
                  required: true
              - in: body
                  name: body
                  description: Delete transaction attributes
                  required: true
                  schema:
                    $ref: '#/definition/Transaction'
            responses:
                '200':
                    description: User transactions retrieved successully
                    schema:
                        type: 'array'
                        items:
                            $ref: '#/definition/TransactionChangeResponse'
                '400':
                    description: Invalid Fields
                '500':
                    description: Internal Server Error
securityDefinitions:
    Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
    Transaction:
        type: object
        id:
          type: integer
          format: int64
        date:
          type: string
          description: transaction date
        details:
          type: string
          description: transaction description
        amount:
          type: number
          description: transaction amount
        balance:
          type: number
          description: account balance
        type:
          type: string
          description: transaction type
        category:
          type: string
          description: transaction category
        notes:
          type: string
          description: notes field for user
    TransactionId:
        type: object
        id:
          type: integer
          format: int64
    TransactionResponse:
        type: 'object'
        properties:
            code:
                type: 'integer'
                format: 'int32'
            type:
                type: 'string'
            body:
              type: object
              properties:
                id:
                  type: integer
                  format: int64
                date:
                  type: string
                  description: transaction date
                details:
                  type: string
                  description: transaction description
                amount:
                  type: number
                  description: transaction amount
                balance:
                  type: number
                  description: account balance
                type:
                  type: string
                  description: transaction type
                category:
                  type: string
                  description: transaction category
                notes:
                  type: string
                  description: notes field for user
    TransactionChangeResponse:
      status:
        type: integer
      message:
        type: string
